version = "1.1.7"

[class]
"dmenu-pass generator" = ""
dmenu-pass = ""
jetbrains-studio = ""
steam = ""
fontforge = ""
work = ""
udiskie = ""
zoom = ""
org-telegram-desktop = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
swappy = ""
duolingo = ""
libreoffice-impress = ""
darktable = ""
dmenu-clipboard = ""
neomutt = ""
xplr = ""
wlfreerdp = "󰀄"
whatsapp-desktop = ""
org-pwmt-zathura = ""
"(?i)alacritty" = ""
sun-awt-x11-xframepeer = ""
"(?i)kitty" = ""
slack = ""
wire = "󰁀"
gcr-prompter = ""
vlc = ""
scli = ""
vimiv = ""
libreoffice-writer = ""
"(?i)firefox" = ""
streamlink-twitch-gui = ""
"(?i)waydroid.*" = "droid"
calibre-gui = ""
bleachbit = ""
songrec = ""
libreoffice-startcenter = ""
org-qutebrowser-qutebrowser = ""
snappergui = ""
kak = ""
virt-manager = ""
plexamp = ""
org-ksnip-ksnip = ""
".*transmission.*" = ""
libreoffice-calc = ""
wayvnc = "󰀄"
paperwork = ""
code-oss = ""
element = ""
mpv = ""
remote-viewer = ""
qutepreview = ""
nm-connection-editor = ""
spotify = ""
cssh = ""
telegramdesktop = ""
discord = ""
"Gimp-2.10" = ""
krita = ""
wireshark-gtk = ""
"(?i)foot" = ""
personal = ""
DEFAULT = ""
kicad = ""
taskwarrior-tui = ""
molotov = ""
sandboxed-tor-browser = ""
dmenu-emoji = ""
pavucontrol = ""
Signal = ""
telegram = ""
rapid-photo-downloader = ""
audacious = ""
burp-startburp = ""
obsidian = ""
shopping = ""
dmenu-browser = ""
qalculate-gtk = ""
chromium = ""
nemo = ""
vncviewer = ""
gsimplecalc = ""
whatsapp-nativefier-d52542 = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"^$" = "^$"
"steam" = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}:{delim}{clients}"
client = "{icon}"
client_fullscreen = "[{icon}]{delim}"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
