# https://github.com/cyrinux/hyprland-autoname-workspaces
[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = ""
"Alacritty" = ""
"foot" = ""
"firefoxdeveloperedition" = ""
"org.telegram.desktop" = ""
"nemo" = ""
"[Ss]team" = ""
"yesplaymusic" = ""
"NotepadNext" = ""
"Code" = ""
"mpv" = ""

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
fcitx = ".*"
"[Ss]team" = "Steam - 新闻.*"
"[Ss]team" = "好友列表.*"
"[Ss]team" = "^$"
#Alacritty = ""

