version = "1.1.5"

[class]
dmenu-emoji = ""
rapid-photo-downloader = ""
".*transmission.*" = ""
gcr-prompter = ""
"Gimp-2.10" = ""
jetbrains-studio = ""
molotov = ""
"(?i)firefox" = ""
dmenu-clipboard = ""
sun-awt-x11-xframepeer = ""
vncviewer = ""
calibre-gui = ""
mpv = ""
vimiv = ""
steam = ""
duolingo = ""
telegramdesktop = ""
xplr = ""
vlc = ""
taskwarrior-tui = ""
org-pwmt-zathura = ""
darktable = ""
songrec = ""
swappy = ""
nemo = ""
libreoffice-impress = ""
spotify = ""
wire = "󰁀"
streamlink-twitch-gui = ""
Signal = ""
chromium = ""
bleachbit = ""
slack = ""
libreoffice-calc = ""
"(?i)kitty" = ""
wireshark-gtk = ""
gsimplecalc = ""
code-oss = ""
"(?i)foot" = ""
libreoffice-startcenter = ""
obsidian = ""
neomutt = ""
element = ""
qalculate-gtk = ""
nm-connection-editor = ""
work = ""
"dmenu-pass generator" = ""
telegram = ""
shopping = ""
scli = ""
"(?i)waydroid.*" = "droid"
sandboxed-tor-browser = ""
wlfreerdp = "󰀄"
remote-viewer = ""
wayvnc = "󰀄"
qutepreview = ""
org-qutebrowser-qutebrowser = ""
udiskie = ""
audacious = ""
kicad = ""
dmenu-pass = ""
personal = ""
whatsapp-desktop = ""
pavucontrol = ""
snappergui = ""
krita = ""
burp-startburp = ""
kak = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
libreoffice-writer = ""
fontforge = ""
discord = ""
dmenu-browser = ""
paperwork = ""
cssh = ""
virt-manager = ""
"(?i)alacritty" = ""
whatsapp-nativefier-d52542 = ""
zoom = ""
plexamp = ""
DEFAULT = ""
org-ksnip-ksnip = ""
org-telegram-desktop = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"[Ss]team" = "^$"
"^$" = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}:{delim}{clients}"
client = "{icon}"
client_fullscreen = "[{icon}]{delim}"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
