version = "1.1.11"

[class]
shopping = ""
neomutt = ""
whatsapp-desktop = ""
org-qutebrowser-qutebrowser = ""
"Gimp-2.10" = ""
gsimplecalc = ""
taskwarrior-tui = ""
nemo = ""
swappy = ""
slack = ""
zoom = ""
rapid-photo-downloader = ""
xplr = ""
org-ksnip-ksnip = ""
krita = ""
molotov = ""
whatsapp-nativefier-d52542 = ""
vimiv = ""
dmenu-pass = ""
wlfreerdp = "󰀄"
calibre-gui = ""
duolingo = ""
".*transmission.*" = ""
element = ""
sun-awt-x11-xframepeer = ""
kak = ""
plexamp = ""
udiskie = ""
audacious = ""
scli = ""
mpv = ""
darktable = ""
jetbrains-studio = ""
telegramdesktop = ""
wire = "󰁀"
snappergui = ""
dmenu-browser = ""
nm-connection-editor = ""
wireshark-gtk = ""
personal = ""
dmenu-clipboard = ""
obsidian = ""
libreoffice-writer = ""
vncviewer = ""
"dmenu-pass generator" = ""
steam = ""
discord = ""
spotify = ""
"(?i)waydroid.*" = "droid"
virt-manager = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
sandboxed-tor-browser = ""
"(?i)firefox" = ""
burp-startburp = ""
"(?i)kitty" = ""
libreoffice-startcenter = ""
streamlink-twitch-gui = ""
gcr-prompter = ""
libreoffice-impress = ""
org-pwmt-zathura = ""
songrec = ""
wayvnc = "󰀄"
fontforge = ""
paperwork = ""
DEFAULT = ""
cssh = ""
dmenu-emoji = ""
work = ""
qutepreview = ""
"(?i)foot" = ""
libreoffice-calc = ""
vlc = ""
bleachbit = ""
"(?i)alacritty" = ""
kicad = ""
remote-viewer = ""
org-telegram-desktop = ""
pavucontrol = ""
telegram = ""
qalculate-gtk = ""
code-oss = ""
Signal = ""
chromium = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"^$" = "^$"
steam = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}{delim}"
workspace_empty = "{id}:{delim}{clients}"
client = "{icon}"
client_fullscreen = "[{icon}]{delim}"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
