version = "1.1.0"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}"
client_active = "{icon}"
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client_dup = "{icon} {counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon} ]{delim}"

[class]
work = ""
darktable = ""
rapid-photo-downloader = ""
taskwarrior-tui = ""
wayvnc = "󰀄"
NotepadNext = ""
nemo = ""
"(?i)firefox" = ""
"(?i)waydroid.*" = "droid"
nm-connection-editor = ""
sandboxed-tor-browser = ""
burp-startburp = ""
"dmenu-pass generator" = ""
"Gimp-2.10" = ""
vlc = ""
dmenu-pass = ""
streamlink-twitch-gui = ""
"(?i)alacritty" = ""
sun-awt-x11-xframepeer = ""
virt-manager = ""
vimiv = ""
whatsapp-desktop = ""
wire = "󰁀"
libreoffice-impress = ""
wlfreerdp = "󰀄"
duolingo = ""
DEFAULT = ""
telegramdesktop = ""
libreoffice-startcenter = ""
"(?i)kitty" = ""
pavucontrol = ""
scli = ""
slack = ""
kak = ""
yesplaymusic = ""
element = ""
swappy = ""
vncviewer = ""
org-qutebrowser-qutebrowser = ""
plexamp = ""
cssh = ""
xplr = ""
dmenu-browser = ""
molotov = ""
qalculate-gtk = ""
code-oss = ""
gsimplecalc = ""
dmenu-clipboard = ""
bleachbit = ""
remote-viewer = ""
neomutt = ""
paperwork = ""
qutepreview = ""
kicad = ""
libreoffice-writer = ""
org-telegram-desktop = ""
"[Ss]team" = ""
chromium = ""
mpv = ""
personal = ""
".*transmission.*" = ""
udiskie = ""
gcr-prompter = ""
jetbrains-studio = ""
obsidian = ""
org-pwmt-zathura = ""
songrec = ""
wireshark-gtk = ""
zoom = ""
discord = ""
krita = ""
Signal = ""
fontforge = ""
chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default = ""
org-ksnip-ksnip = ""
telegram = ""
snappergui = ""
shopping = ""
spotify = ""
whatsapp-nativefier-d52542 = ""
"(?i)foot" = ""
libreoffice-calc = ""
dmenu-emoji = ""
calibre-gui = ""
audacious = ""

[class_active]

[initial_class]

[initial_class_active]

[title_in_class]

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
fcitx = ".*"
"[Ss]team" = "^$"
