abbr -a dbl 'docker build'
abbr -a dcin 'docker container inspect'
abbr -a dcls 'docker container ls'
abbr -a dclsa 'docker container ls -a'
abbr -a dib 'docker image build'
abbr -a dii 'docker image inspect'
abbr -a dils 'docker image ls'
abbr -a dipu 'docker image push'
abbr -a dipru 'docker image prune -a'
abbr -a dirm 'docker image rm'
abbr -a dit 'docker image tag'
abbr -a dlo 'docker container logs'
abbr -a dnc 'docker network create'
abbr -a dncn 'docker network connect'
abbr -a dndcn 'docker network disconnect'
abbr -a dni 'docker network inspect'
abbr -a dnls 'docker network ls'
abbr -a dnrm 'docker network rm'
abbr -a dpo 'docker container port'
abbr -a dps 'docker ps'
abbr -a dpsa 'docker ps -a'
abbr -a dpu 'docker pull'
abbr -a dr 'docker container run'
abbr -a drit 'docker container run -it'
abbr -a drm 'docker container rm'
abbr -a 'drm!' 'docker container rm -f'
abbr -a dst 'docker container start'
abbr -a drs 'docker container restart'
abbr -a dsta 'docker stop (docker ps -q)'
abbr -a dstp 'docker container stop'
abbr -a dtop 'docker top'
abbr -a dvi 'docker volume inspect'
abbr -a dvls 'docker volume ls'
abbr -a dvprune 'docker volume prune'
abbr -a dxc 'docker container exec'
abbr -a dxcit 'docker container exec -it'

abbr -a dcup 'docker compose up'
abbr -a dcupd 'docker compose up -d'
abbr -a dcdn 'docker compose down'
abbr -a dcl 'docker compose logs'
abbr -a dclf 'docker compose logs -f'
abbr -a dclF 'docker compose logs -f --tail 0'
abbr -a dcrestart 'docker compose restart'
